
/*
 *	This file was automatically generated by dbusxx-xml2cpp; DO NOT EDIT!
 */

#ifndef __dbusxx__audio_source_server_glue_h__ADAPTOR_MARSHAL_H
#define __dbusxx__audio_source_server_glue_h__ADAPTOR_MARSHAL_H

#include <dbus-c++/dbus.h>
#include <cassert>

namespace ipcam {
namespace Media {

class AudioSource_adaptor
: public ::DBus::InterfaceAdaptor
{
public:

    AudioSource_adaptor()
    : ::DBus::InterfaceAdaptor("ipcam.Media.AudioSource")
    {
        bind_property(Channels, "u", true, true);
    }

    ::DBus::IntrospectedInterface *introspect() const 
    {
        static ::DBus::IntrospectedMethod AudioSource_adaptor_methods[] = 
        {
            { 0, 0 }
        };
        static ::DBus::IntrospectedMethod AudioSource_adaptor_signals[] = 
        {
            { 0, 0 }
        };
        static ::DBus::IntrospectedProperty AudioSource_adaptor_properties[] = 
        {
            { "Channels", "u", true, true },
            { 0, 0, 0, 0 }
        };
        static ::DBus::IntrospectedInterface AudioSource_adaptor_interface = 
        {
            "ipcam.Media.AudioSource",
            AudioSource_adaptor_methods,
            AudioSource_adaptor_signals,
            AudioSource_adaptor_properties
        };
        return &AudioSource_adaptor_interface;
    }

public:

    /* properties exposed by this interface, use
     * property() and property(value) to get and set a particular property
     */
    ::DBus::PropertyAdaptor< uint32_t > Channels;

public:

    /* methods exported by this interface,
     * you will have to implement them in your ObjectAdaptor
     */

public:

    /* signal emitters for this interface
     */

private:

    /* unmarshalers (to unpack the DBus message before calling the actual interface method)
     */
};

} } 
#endif //__dbusxx__audio_source_server_glue_h__ADAPTOR_MARSHAL_H
